### PR TITLE
Corrections to new tmp folder version

### PR DESCRIPTION
**Pull request by brittonbowman**
comments in line.

### CODE REVIEW

**Comment by XDGFX** [comment]
A couple of things that don't work for me with this version; 

`install_directory` is relative to your Plex machine, so copying from tmp folder back to `install_directory` throws an error when Plex machine ≠ PPP machine

There were a few other things as well - I will implement the various other fixes though

**Comment by XDGFX** [comment]
I've implemented the # skipping for m3u tags, some of the other additions don't seem to work for me - are you running PPP on the same machine as Plex?

**Comment by brittonbowman** [comment]
I could not work out a way to post the plex playlist from the TMP folders as they are not accessible for post call, so need they need to moved to the same machine as the running script for post to access.

Mine is installed on a networked drive (same as music and playlists) that is accessible to plex server and all other pc's in the network, so it make life easier in that I can run from either plex or other pc. (both are linux).

**Comment by brittonbowman** [comment]
tempfile.mkdtemp
Creates a temporary directory in the most secure manner possible. There are no race conditions in the directory’s creation. **The directory is readable, writable, and searchable only by the creating user ID**.

**Comment by XDGFX** [comment]
Looks like using a secure temp folder isn't really useful in this scenario. Closing the request

**Pull request closed without merging**
