### PR TITLE
Add self-signed certificate compatibility by optionally ignoring certificate validity

### PR DESCRIPTION
**Pull request by dan0v**

### CODE REVIEW

**Comment by XDGFX** [comment]
Looks good - could you explain what the self signed ssl certificates are used for? Is it something to do with having the Plex server accessed remotely or through a custom domain or something?

Cheers

**Comment by dan0v** [comment]
Well, lets say for example I have my Plex server behind a reverse proxy at `plex.mydomain.com`. I have Plex configured to only accept HTTPS requests (HTTP is unresolved), so I can't point PPP to `http://ipOfPlexServerOnMyNetwork:32400`.

This is fine when accessing `https://plex.mydomain.com` via the reverse proxy, but accessing `https://ipOfPlexServerOnMyNetwork:32400`, the SSL certificate I've given Plex is invalid for this address, as it's valid for `plex.mydomain.com`. There are similar issues with the certificates plex generates for itself (like `*.a1s2d3f4g5h6j4s5s6a5dljghsd.plex.direct.`) when you turn Remote Access on.

I don't want to forward port 32400 via my reverse proxy, so I'm forced to access it over unsecure HTTPS within my own network because of its bad certificate. Like a browser, however, you need to manually specify that certificate validity doesn't need to be checked by the Requests module, otherwise it freaks out, warning you because there might be a man-in-the-middle attack occurring. Since I'm on my own network, I'm not too worried about this, so would like to ignore these warnings and allow the program to continue, trusting the invalid certificate. Without the fix in this PR, PPP crashes due to `ERROR: Issue encountered when attempting to list detailed sections info.
ERROR: HTTPSConnectionPool(host='192.168.0.15', port=32400): Max retries exceeded with url: /playlists/?X-Plex-Token=myToken(Caused by SSLError(CertificateError("hostname '192.168.0.15' doesn't match '*.a1s2d3f4g5h6j4s5s6a5dljghsd.plex.direct` when trying to GET or POST data to Plex, pretty much immediately terminating the program.

**Comment by dan0v** [comment]
I also think it's nice to include a demo variables / config file, as I didn't have access to an interactive terminal when I first tried to run PPP, so it'd be helpful to have the option to just change the variables file if you don't want to go through the setup process.

**Comment by XDGFX** [comment]
Ah perfect I understand! And whoops I missed that last commit, I'll add an example config file

**Pull request merged**
